### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by mangeshsable1975** [Sangram2905/Stock_Market_BOT#2]
ImportError: numpy.core.multiarray failed to import

**Comment by mangeshsable1975** [comment]
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS G:\SANGRAM> & C:/Users/admin/AppData/Local/Programs/Python/Python39/python.exe "g:/SANGRAM/Stock_Market_BOT/Stock record High and Low indicator 5 BOTs updated.py"     
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "g:\SANGRAM\Stock_Market_BOT\Stock record High and Low indicator 5 BOTs updated.py", line 38, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
PS G:\SANGRAM>

**Comment by mangeshsable1975** [comment]
this is very good programm you have written
i am not good in programming
But having in some knowadge in NSE data reading.d
due to working in a pvt. company i am unalbe to stay connected to nse website over computer as restricted by company policy.
only option is mobile for data view/analize, but it is very hectic and time consuming in office.
i have desktop at home in which this programm install.
i would like to add telegram bot (i have my telegram bot created for personal use)
can we add telegram bot to your code (print = to transer to telegram bot)
my contact no. 7666023805
it will be my pleasue to talk to you over phone

thanking you

mangesh sable

**Comment by Sangram2905** [comment]
Hi, Sorry for late response.
This are sample programs in my start of learning Stock market + Python 

Follow data for trader  https://youtube.com/channel/UClY1Cdb-KfZuKuTbajEbwMQ

One of the best Python base Algo trading programs 

Sorry not modifying any code for telegram as it's purely for education only.
